# Generated by Django 2.1.3 on 2020-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='chicago_collision_data',
            field=models.FileField(blank=True, null=True, upload_to='json/chicago_collision_data/'),
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='flight_call',
            field=models.FileField(blank=True, null=True, upload_to='json/flight_call'),
        ),
        migrations.AddField(
            model_name='book',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='light_levels',
            field=models.FileField(blank=True, null=True, upload_to='json/light_levels'),
        ),
    ]
